Refactoring based on SOLID Principles
addisalemseifu/library-app-ruby pull request #5
Opened 2023-09-04 12:53 UTC by marvin-nyalik

In this branch:

- We followed SOLID principles.
- We made sure YAGNI, KISS, and DRY rules are applied
- We made sure that the role of `main.rb` is only to start your code and ask the user for the initial choice of options (or to quit).
- We extracted some pieces of logic into separate class(es) i.e Register and Director class.

Here's the new look of the main.rb class
![refactoring](https://github.com/addisalemseifu/library-app-ruby/assets/81169099/06e3c88e-4f0e-4315-8d7d-ef2e8abe7f11)
@addisalemseifu and @marvin-nyalik . Let us know if there are any changes required.

2023-09-04 14:55 UTC, iambenkis commented
Hi @marvin-nyalik , @addisalemseifu  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

- [ ] You have submitted a pair programming project where one partner only edited the README file without making a real contribution to the codebase, Kindly ensure that both of you contribute to the codebase 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@iambenkis` in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-05 10:37 UTC, LionRouge1 commented on app.rb
- [ ] Nice work defining the methods in the `app.rb` file :clap: However in the spirit of make our code better, it would be nice   to put all this method in a class named `App`
```ruby
class App
  def initialize
    @books = [ ]
    @people = [ ]
    @rentals =[ ]
  end

  def list_all_book
  puts 'You have no book in the cart!' if Book.book_list.empty?
  Book.book_list.each do |book|
    puts "Title: #{book.title}, Author: #{book.author}"
  end
  Main.new.prompter
  Director.new.director
end

def list_all_people
  persons = Student.student_list + Teacher.teacher_list
  persons.length
  persons.each do |person|
    puts "Name: #{person.name}, Age: #{person.age}"
  end
  Main.new.prompter
  Director.new.director
end

def per_met
  puts 'student'
  print 'Age:'
  age = gets.chomp
  print 'Name:'
  name = gets.chomp
  print 'classroom:'
  classroom = gets.chomp
  Student.new(classroom, age, name)
end

def create_a_person
  puts 'Do uou want to create a student (1) or a teacher (2)? [Input the number]'
  person_type = gets.chomp
  if person_type == '1'
    per_met
  elsif person_type == '2'
    puts 'teacher'
    print 'Age:'
    age = gets.chomp
    print 'Name:'
    name = gets.chomp
    print 'specialization:'
    specialization = gets.chomp
    Teacher.new(specialization, age, name)
  end
  puts 'Person created successfully!'
  Main.new.prompter
  Director.new.director
end

def create_a_book
  print 'Title:'
  title = gets.chomp
  print 'Author:'
  author = gets.chomp
  book = Book.new(title, author)
  puts 'Book created successfully!'
  puts book.rental.length
  puts Book.book_list[0].title
  Main.new.prompter
  Director.new.director
end

def create_a_rental
  book_choice = my_choice
  person_choice = myperson_choice
  date = my_date
  Rental.new(date, book_choice, person_choice)
  puts 'Rental created successfully'
  Main.new.prompter
  Director.new.director
end

def my_choice
  puts 'Select a book from the following list by number'
  Book.book_list.each_with_index do |book, index|
    puts "#{index}) Title: #{book.title}, Author: #{book.author}"
  end

  choice_of_book = gets.chomp.to_i
  Book.book_list[choice_of_book]
end

def myperson_choice
  persons = Student.student_list + Teacher.teacher_list
  puts 'Select a person from the following list by number (not id)'
  persons.each_with_index do |person, index|
    puts "#{index}) [#{person.class}]
     Name: #{person.name}, ID: #{person.id}, Age: #{person.age}"
  end

  choice_of_person = gets.chomp.to_i
  persons[choice_of_person]
end

def my_date
  print 'Date: '
  gets.chomp
end

def list_all_rentals
  persons = Student.student_list + Teacher.teacher_list
  print 'ID of person: '
  id = gets.chomp
  renter = persons.select do |rental|
    rental.id == id.to_i
  end
  puts 'Rentals:'
  puts 'Date: '
  renter[0].rental.each do |rental|
    puts "Date: #{rental.date}, Book \"#{rental.book.title}\" by #{rental.book.author}"
  end
  Main.new.prompter
  Director.new.director
end

def exit_app
  puts 'Goodbye'
  exit
end
end
```

2023-09-05 10:40 UTC, LionRouge1 requested changes
Hi **Team**, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-05 10:40 UTC, LionRouge1 commented on app.rb
> +  Director.new.director
- [ ] As you can notice, this code has been repeated so many time in different method and that is against the DRY principle. Kindly let find a way to only run this in the `main.rb` file

2023-09-05 10:40 UTC, LionRouge1 commented on main.rb
- [ ] To avoid repeating this :point_down: code 
  ```ruby
  Main.new.prompter
  Director.new.director
  ```
  in the `app.rb` file, we can make use of `while` condition in our `main.rb` file. The `main.rb` file could look like this :point_down: 

```ruby
# *the refactor contents of main.rb file
require "./app.rb"

def main
  app = App.new()

  response = nil

  puts "Welcome to School Library App!\n\n"
  while response != "7"
    puts "Please choose an option by entering a number:"
    puts "1 - List all books"
    puts "2 - List all people"
    puts "3 - Create a person"
    puts "4 - Create a book"
    puts "5 - Create a rental"
    puts "6 - List all rentals for a given person id"
    puts "7 - Exit"
    response = gets.chomp

    case response
    when "1"
      app.list_all_book()
    when "2"
      app.list_all_people()
    when "3"
      app.create_person()
    when "4"
      app.create_book()
    when "5"
      app.create_rental()
    when "6"
      app.list_rentals_for_person_id()
    when "7"
      puts "Thank you for using this app!"
    end

    puts "\n"
  end
end

main()
```

2023-09-05 13:17 UTC, LionRouge1 approved these changes
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Highlights
- Great job, making the changes :+1: 
- Nice work you meet all the requirements :1st_place_medal: 
- All linters passed :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-05 13:22 UTC, merged